name: PR Checks

on:
  pull_request:
    branches: [ "main", "develop" ]
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/CI.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: read
      security-events: write

  smoke-tests:
    name: Smoke Test (docker-compose)
    needs: ci
    uses: ./.github/workflows/smoke-tests.yml
    secrets: inherit
    permissions:
      contents: read

