name: Push Checks

on:
  push:
    branches: ["main", "develop"]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/CI.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: read
      security-events: write

  cd:
    name: CD
    needs: ci
    uses: ./.github/workflows/CD.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
